### ISSUE TITLE
why sharpkit only  star 58

### ISSUE THREAD

**Issue by liangjl76** [SharpKit/SharpKit#20]
https://github.com/sq/JSIL
MIT/X11
star 1181

https://github.com/bridgedotnet/Bridge
Apache License, Version 2.0
star 553

https://github.com/nikhilk/scriptsharp
Apache 2.0 License
star 583

https://github.com/SharpKit/SharpKit
GPL
star 58

why?

**Comment by Arakis** [comment]
This is an interesting question. Maybe, because we never tried to promote it with social media. SharpKit is extremly flexible, nearly "everything" is possible.

Sharpkit is a hidden secret ;)

Another matter could be, it was commercial in the history. Now it's completly open source.
