### ISSUE TITLE
Website unreachable

### ISSUE THREAD

**Issue by mylemans** [SharpKit/SharpKit#22]
@Arakis @danelkhen Is it normal that I cannot reach the website anymore? http://sharpkit.net/

**Comment by reddyBell** [comment]
Still not accessible, I am new to it so this means there is no documentation available :/

**Comment by YeDaxia** [comment]
@Arakis @danelkhen Can you guys push the documentation to this repo?  I want to learn it~

**Comment by Arakis** [comment]
I wrote Dan-el now an mail, i hope we can find a proper solution.

**Comment by Arakis** [comment]
I've have good news: The documentation is uploaded here now:
https://sharpkit.github.io
