### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by michael-dartfish** [SharpKit/SharpKit#23]
Hello,
The provided installer works perfectly with Visual Studio 2012 & 2015, but unfortunately not with Visual Studio 2017. Does anyone know which files must be copied where ?

**Comment by danelkhen** [comment]
Try this:
Look for a folder named SharpKit in .net framerwork folders e.g.: `C:\Windows\Microsoft.NET\Framework\v4.0.30319`, and copy it to wherever your tools are run from. You can do a search for msbuild.exe, and copy this folder to wherever that is located.
